In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6],[7, 8, 9],[10, 11, 12]])

print(a.shape)
print(b.shape)
print(a+b)


#here the array a stretches to match the shape of b
#this is called broadcasting

(3,)
(3, 3)
[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [13]:

c = np.zeros(3)
# c = c + 1
print(c.shape)
c = np.zeros((3,))
print(c.shape)

(3,)
(3,)


In [14]:
#vector indexing operations on 1-D vectors
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices    -1 is placeholder

#reshape is for rows and columns 
#-1,2 means x(rows) * 2(columns) = 6 elements in total ,, therefore x = 3
print(f"a.shape: {a.shape}, \na= {a}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]
